config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories, only: [:index, :show, :new, :create, :destroy] do
    resources :activities, only: [:new, :create, :destroy]
  end
  root "categories#index"
  # get "/welcome_page", to: "welcome_page#index"
  resources :welcome_page, only: [:index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_activities, dependent: :destroy
  has_many :activities, through: :category_activities, dependent: :destroy, class_name: 'Activity'
  validates :name, :icon, :user_id, presence: true

  def total_amount
    activities.sum(:amount)
  end

  def desc_activities
    activities.order(created_at: :desc)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user_id: current_user.id)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @activities = @category.desc_activities
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @user = current_user
    @category = @user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="category">
  <div class="icon-name">
    <img src='<%= category.icon %>' class="icon"/>
    <span class="cname">
      <p><%= category.name %></p>
      <p class="ctime"><%= category.created_at.to_date%></p>
    </span>
  </div>
  <p class="tamount">
    $<%=category.total_amount%>
  </p>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name ,placeholder: "Enter the name of the category", autofocus:true %>
  </div>

  <div class="field">
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon , placeholder: "Enter photo url" %>
  </div>

  <div class="submit">
    <%= form.submit "Save", class: "link_to" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<% content_for :page_title, "CATEGORIES" %>

<main>
  <header>
    <% if user_signed_in? %>
        <%= render "layouts/nav" %>
    <%end%>
    <div class="extra-links-container">
      <div class="extra-links">
        <p class="recent">Most recent</p>
        <p class="ancient">Most ancient</p>
      </div>
    </div>
  </header>
  <p class="suc_notice"><%= notice %></p>
  <p class="err_alert"><%= alert %></p>

  <%if @categories.empty?%>
    <p class="note">You have no categories yet!</p>
  <%end%>

  <div id="categories">
    <% @categories.each do |category| %>
      <%= link_to render(category), category_path(category) %>
    <% end %>
  </div>

  <div  class="cat-btn-container">
    <%= button_to "New category", new_category_path, class: "cat-btn", method: :get %>
  </div>
</main>

app/views/categories/new.html.erb
<% content_for :page_title, "NEW CATEGORY" %>

<div class="new_cat">
  <h1>Add a new category</h1>
  <div class="headline-btn">
    <%= link_to " < ", categories_path, class:"link_to back"%>
  </div>
  <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<% content_for :page_title, "DETAILS" %>

<main>
  <header>
    <ul class="navbar">
      <li>
        <%= button_to categories_path, method: :get, class: "back_to" do %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
      </li>
      <li class="page-title"> <%= yield :page_title %> </li>
      <li class="searchbtn">
        <i class="fa-solid fa-search"></i>
      </li>
    </ul>
  </header>

  <p class="suc_notice"><%= notice %></p>
  <p class="err_alert"><%= alert %></p>

  <p class="tamountE"> Total amount:          <%= @category.total_amount%> </p>

  <div id="activities">
    <% @activities.each do |activity| %>
      <%= render activity %>
    <% end %>
  </div>

  <%if @activities.empty?%>
    <p class="note">This category is empty!</p>
  <%end%>

  <div >
    <div class = "links" >
      <%= button_to "New activity", new_category_activity_path(@category) , class: "link_to", method: :get %>
      <%= button_to "Delete Category", category_path(@category.id), method: :delete, class: "link_to delete" %>
    </div>
  </div>
</main>