config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories, only: [:index, :show, :new, :create, :destroy] do
    resources :activities, only: [:new, :create, :destroy]
  end
  root "categories#index"
  # get "/welcome_page", to: "welcome_page#index"
  resources :welcome_page, only: [:index]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :categories, through: :category_activities
  has_many :category_activities, dependent: :destroy
  validates :name, :amount, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show edit update destroy]

  # GET /activities or /activities.json
  def index
    @category = Category.find(params[:category_id])
    @activities = @category.activities
  end

  # GET /activities/1 or /activities/1.json
  def show
    @activity = Activity.find(params[:id])
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    @category = Category.find(params[:category_id])
  end

  # GET /activities/1/edit
  def edit; end

  # POST /activities or /activities.json
  def create
    user = current_user
    @activity = Activity.new(activity_params)
    @activity.author = user
    @category_activity = CategoryActivity.new(activity: @activity, category_id: params[:category_id])

    if @activity.save && @category_activity.save
      redirect_to category_path(params[:category_id]), notice: 'Activity created successfully'
    else
      redirect_to category_path(params[:category_id]), alert: 'An error occured when creating the activity'
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    @category = Category.find(params[:category_id])

    respond_to do |format|
      format.html { redirect_to category_path(@category.id), notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:category).permit(:name, :amount)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>" class="activity">
  <div>
    <p>
      <strong>Name:</strong>
      <%= activity.name %>
    </p>
    <p>
      <strong>Amount:</strong>
      <%= activity.amount %>
    </p>
  </div>
  <div>
    <%= button_to "Delete", category_activity_path(@category.id, activity.id), class: "link_to delete", method: :delete %>
  </div>
</div>

app/views/activities/_form.html.erb
<%= form_with model: @activity, url: category_activities_path, method: :post, local: true, scope: :category do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div  class = "field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name , required: true, placeholder: "What did you just buy?" %>
  </div>

  <div  class = "field">
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount , required: true, placeholder: "How much did it cost?"%>
  </div>

  <p>Choose categories</p>
  <i><%=@category.name%> has been selected for you</i>
  <div>
    <%= render "select_cat_form", categories: current_user.categories%>
  </div>
  <div  class = "submit">
    <%= form.submit 'Save', class: "link_to" %>
  </div>
</div>
<% end %>

app/views/activities/_select_cat_form.html.erb
<%categories.each do |category|%>
  <div class="form-check">
      <input name="categories" type="checkbox"  <%="checked disabled" if category.id.to_s == params[:category_id]%> id="check-b" value=<%=category.id%>>
      <label for="check-b">
          <%=category.name%>
      </label>
  </div>
<%end%>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Activities</h1>

<div id="activities">
  <% @activities.each do |activity| %>
    <%= render activity %>
  <% end %>
</div>

app/views/activities/new.html.erb
<% content_for :page_title, "NEW ACTIVITY" %>

<div class = "new_act">
  <h1>Add a new Transaction</h1>
  <div class="headline-btn">
    <%= link_to "<", category_path(@category) , class:"link_to back" %>
  </div>
  <%= render "form", activity: @activity %>
</div>
<br>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%#= link_to "Edit this activity", edit_activity_path(@activity) %> |
  <%= link_to "Back to activities", category_activities_path(@category) %>

  <%#= button_to "Destroy this activity", @activity, method: :delete %>
</div>