config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories, only: [:index, :show, :new, :create, :destroy] do
    resources :activities, only: [:new, :create, :destroy]
  end
  root "categories#index"
  # get "/welcome_page", to: "welcome_page#index"
  resources :welcome_page, only: [:index]
end

app/views/layouts/_nav.html.erb
<ul class="navbar">
    <li class="dropdown">
        <a class="btn dropbtn"><i class="fa-solid fa-bars"></i></a>
            <div class="dropdown-content">
            <div class="deco"></div>
            <%= button_to 'Home',  categories_path, class: "nav-link", method: :get %>
            <%= button_to 'Sign out', destroy_user_session_path, class: "nav-link", method: :delete %>
            </div>
    </li>
    <li class="page-title"> <%= yield :page_title %> </li>
    <li class="searchbtn">
        <i class="fa-solid fa-search"></i>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/48a75e5b8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>